version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-container-db
    environment:
      POSTGRES_USER: mono
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always